const StudentTypes = {
  UPDATE_INFO: 'UPDATE_INFO',
  UPDATE_INFO_SUCCESS: 'UPDATE_INFO_SUCCESS',
  UPDATE_INFO_FAILURE: 'UPDATE_INFO_FAILURE',
  UPDATE_INFO_CLEAR: 'UPDATE_INFO_CLEAR',
}

export default StudentTypes
