const ContractTypes = {
    CLEAR_CONTRACT_STATE: 'CLEAR_CONTRACT_STATE',
    GET_CONTRACT_LIST: 'GET_CONTRACT_LIST',
    UPDATE_CONTRACT_LIST: 'UPDATE_CONTRACT_LIST',
    CREATE_CONTRACT: 'CREATE_CONTRACT',
    UPDATE_CONTRACT: 'UPDATE_CONTRACT',
  }
  
  export default ContractTypes
  