const ContractTypes = {
  CLEAR_CONTRACT_STATE: 'CLEAR_CONTRACT_STATE',

  GET_CONTRACT_LIST: 'GET_CONTRACT_LIST',
  GET_CONTRACT_LIST_SUCCESS: 'GET_CONTRACT_LIST_SUCCESS',
  GET_CONTRACT_LIST_FAILURE: 'GET_CONTRACT_LIST_FAILURE',

  CREATE_CONTRACT: 'CREATE_CONTRACT',
  UPDATE_CONTRACT: 'UPDATE_CONTRACT',
}

export default ContractTypes
