const TeacherTypes = {
  CLEAR_TEACHER_STATE: 'CLEAR_TEACHER_STATE',
  GET_TEACHER_INFO: 'GET_TEACHER_INFO',
  GET_TEACHER_LIST: 'GET_TEACHER_LIST',
  COUNT_TEACHERS: 'COUNT_TEACHERS',
  UPDATE_TEACHER_LIST: 'UPDATE_TEACHER_LIST',
  UPDATE_CURRENT_TEACHER: 'UPDATE_CURRENT_TEACHER',
  UPDATE_NUMBER_OF_TEACHERS: 'UPDATE_NUMBER_OF_TEACHERS',

  TEACHER_GET_INFO: 'TEACHER_GET_INFO',
  TEACHER_GET_INFO_SUCCESS: 'TEACHER_GET_INFO_SUCCESS',
  TEACHER_GET_INFO_FAILURE: 'TEACHER_GET_INFO_FAILURE',

  TEACHER_UPDATE_INFO: 'TEACHER_UPDATE_INFO',
  TEACHER_UPDATE_INFO_SUCCESS: 'TEACHER_UPDATE_INFO_SUCCESS',
  TEACHER_UPDATE_INFO_FAILURE: 'TEACHER_UPDATE_INFO_FAILURE',
  TEACHER_UPDATE_INFO_CLEAR: 'TEACHER_UPDATE_INFO_CLEAR',
}

export default TeacherTypes
