const TeacherTypes = {
  CLEAR_TEACHER_STATE: 'CLEAR_TEACHER_STATE',
  GET_TEACHER_INFO: 'GET_TEACHER_INFO',
  GET_TEACHER_LIST: 'GET_TEACHER_LIST',
  COUNT_TEACHERS: 'COUNT_TEACHERS',
  UPDATE_TEACHER_LIST: 'UPDATE_TEACHER_LIST',
  UPDATE_CURRENT_TEACHER: 'UPDATE_CURRENT_TEACHER',
  UPDATE_NUMBER_OF_TEACHER: 'UPDATE_NUMBER_OF_TEACHER',
}

export default TeacherTypes
