const UserTypes = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_GOOGLE_START: 'LOGIN_GOOGLE_START',
  LOGIN_FACEBOOK_START: 'LOGIN__FACEBOOK_START',
}

export default UserTypes
